[package]
name = "practice1_compgeo"
version = "0.1.0"
authors = ["Alberto Natanael Medel Piña <natanael_pi@ciencias.unam.mx>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
